### ISSUE TITLE
OSError: [WinError 193] %1 não é um aplicativo Win32 válido

### ISSUE THREAD

**Issue by ramonbss** [brianrho/fpmatch#2]
I know you not code this dll. This thread is only to ask you to add your pc configuration into the readme. Things like you Python version and your Windows version.

Mine configuration is:
Windows 10 Pro 64 bit
Python 3.7.4 ( the lastest stable version at the moment of this post )

[EDIT1]
Full trackback:
**Traceback (most recent call last):
  File "fpmatch.py", line 117, in <module>
    arth = WinDLL('ARTH_DLL')
  File "D:\Win\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 não é um aplicativo Win32 válido**

[EDIT2]
My python is installed in another partition "D:" while the OS is installed at "C". Just to add more infos

**Comment by brianrho** [comment]
I don't use that machine any longer, but it was a regular Windows 10 Home with with a Python 3 installation, either 3.6 or 3.7, don't remember. In any case, it should've worked without issues unless something's drastically changed between versions. Make sure the DLL is in the same folder as the script. If it still doesn't work, try using some gibberish DLL name, and see if the error changes or not.

**Comment by brianrho** [comment]
If your problem's solved, I'll be closing this.
