### ISSUE TITLE
Support for Linux 

### ISSUE THREAD

**Issue by jcdesignweb** [brianrho/fpmatch#4]
Hi Brian! Thank you for your project is really amazing, really I hope that you can help me!. I have connected my fingerprint to my pc through USB using a USB TTL. But I have not idea how can I use it.. Can you give me some idea about this please?

TIA !

**Comment by brianrho** [comment]
If you don't even know how to use the sensor yet, I'm afraid this isn't the place to be. This project/repo is for performing matching on a PC, when you've gone beyond the basics and know exactly what you need. You should first start with libraries like [this](https://pypi.org/project/pyfingerprint/) that enable your PC interact with the sensor, and then google whatever else you need to know. Good luck.
